### ISSUE TITLE
Feature query can return features that aren't visible at the query position

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#1045]
If I perform a feature query at the mouse location in the following screenshot, I would expect that any result I get back would be for the building that is evidently under my cursor:

![screenshot from 2016-10-28 12 31 38](https://cloud.githubusercontent.com/assets/3371850/19822004/4e3213b2-9d2f-11e6-903e-739c965ba93f.png)

What happens instead is that instead of One World Trade Center, I get back a result for "300 Vesey Street":
```
 { "id": "250568900.000000","area": "6631.000000","kind": "building","name": "300 Vesey Street","height": "79.400000","source": "openstreetmap.org","volume": "526501.000000","min_zoom": "13.000000","sort_key": "475.000000","short_name": "NYMEX","addr_street": "North End Avenue","addr_housenumber": "1" }
```
The reason for this becomes clear when we visualize the selection buffer used for this query:

![screenshot from 2016-10-28 12 31 53](https://cloud.githubusercontent.com/assets/3371850/19822057/8af124aa-9d2f-11e6-8431-afa19d1ef572.png)

The upper portion of OWTC is evidently not a selectable feature with the current scene file. The current feature selection process _removes_ any non-selectable geometry from the view frustum when generating the selection buffer (https://github.com/tangrams/tangram-es/blob/master/core/shaders/polygon.vs#L80-L87). This means that the building behind OWTC (300 Vesey St) is rendered into the selection buffer in fragments that are occluded by OWTC in the actual color buffer.

In this particular scenario, I knew the correct result of the feature query, but in the general case I would have no way to determine whether the query result applies to the feature that is visible under my cursor or something _behind_ it, which severely limits the utility of the query.

This scenario is probably quite common in feature-dense areas, it only took about 25 seconds to find this case.

**Comment by blair1618** [comment]
Here's what I think _should_ happen:

Features that are non-selectable in the scene should be drawn to the selection buffer as black, to occlude the same features that they do in the color buffer. 

In the case above and similar situations, the result is that the query would return nothing. Returning nothing is not ideal, (I clearly wanted an answer!) but returning nothing is much, _much_ better than returning an incorrect result.

**Comment by hjanetzek** [comment]
On the other hand, say you want to select the selectable Central Park with a non-selectable playground drawn on top then the position at which you can select Central Park will be confusing for the user in my opinion. 

Since the problem you describe seems to be regarding extruded objects one solution could be to use selectionColor=1 for all extruded meshes that don't have a selectionColor set. This could later be made explicit with `obstacle: true` style property.

**Comment by bcamper** [comment]
The park case, where there are many features on top that you usually don't
want to occlude the "general" result, is why I implemented it this way in
JS.

I've been hesitant to introducing another style parameter for this, but...
I'm warming to it :)

**Comment by nvkelso** [comment]
Are there 2 different use cases, more like a scene property akin to
animation?

   1. Developer’s desire to introspect anything and everything
   2. Designers desire to only make some features interactive

**Comment by bcamper** [comment]
The developer's case (introspect everything) is covered by the
`setIntrospection()` mode added in recent Tangram versions (currently used
in Play).

We're actually talking about two potentially different design scenarios:

1. Wanting to have a large polygon, like a park, be entirely selectable,
even when other features (baseball fields, paths, etc.) are drawn on top of
it (e.g. the whole thing is logically "the park").

2. Not wanting some features that are *behind* others to "show through" the
occluding object (e.g. a road that is behind a building, where the road is
interactive but the building is not; see example in this ticket). As
pointed out here, this mostly arises with extruded/3d geometry, and tilted
views (though can happen in Tangram JS top-down as well).

**Comment by blair1618** [comment]
Adding a parameter to enable selection occlusion (e.g. `obstacle: true`) doesn't solve the problem described at the start of this issue. In the example scenario, we see that One World Trade Center is evidently composed of several extruded polygons with different feature properties. A user may think that they have correctly applied the `obstacle: true` parameter, but in fact they have only applied it to some of those building polygons. Then the user makes the selection query and gets back "300 Vesey St". Now there are two possible explanations for that result, either the result is in fact the correct feature, or the `obstacle` property doesn't apply to the building under the cursor. Once again, for features that aren't known _a priori_ there is no way for the user to know for sure that the query result is actually the feature under their cursor.

**Comment by hjanetzek** [comment]
So how about rendering non-selectable extruded features to the selection framebuffer by default?

**Comment by hjanetzek** [comment]
https://github.com/tangrams/tangram-es/pull/1049

**Comment by karimnaaji** [comment]
Another option is to leave two separate ways of performing selection queries on the API side, `selectVisibleFeatures` and `selectFeatures` where `selectVisibleFeatures` would perform a _you get what you see_ type of selection, drawing all the features even non-selectable ones; `selectFeatures` would draw only features that are made selectable, giving more results when selecting features hidden/occluded under areas covered by other features like parks but potentially selecting hidden polygons.

**Comment by blair1618** [comment]
@hjanetzek Yeah, the problem here does seem to be a consequence of extruding 3D geometry. If everything were on a 2D plane then I don't think it would be surprising that pointing to a polygon inside a larger polygon might return the larger polygon. Up to now, we've been careful in the design of tangram to not treat 3D geometry as a special case, but maybe it would help here. 

@karimnaaji Making two query functions is an interesting approach, but raises implementation questions. If we provide a function to select from all features, regardless of the `interactive` parameter, then that implies always storing the feature properties for every map feature, a big waste of memory in most use cases.

**Comment by karimnaaji** [comment]
@blair1618 No, I'm not proposing to allow to select _all_ of the features, only visible features as features that can be seen, meaning drawing non-tagged feature as black without storing their properties. 
In that implementation it shouldn't be that complicated, we can have a simple shader switch from one to another where `selectVisibleFeatures` does't hard break on that statement https://github.com/tangrams/tangram-es/blob/master/core/shaders/polygon.vs#L85.

**Comment by blair1618** [comment]
@karimnaaji I see what you mean, yeah that makes sense. So to summarize your idea, we would have two similar functions:

1. Render only the `interactive: true` features into a selection buffer and return a feature if a selection color is found.
2. Render all features into a selection buffer, with non-interactive features rendered with color `(0,0,0)`, and return a feature if a selection color is found.

This could certainly be implemented, but I'd like to think a bit more about the use cases of feature selection to make sure that we're making a meaningful division of functionality.
